### ISSUE TITLE
Styling the component, for instance borderBottom

### ISSUE THREAD

**Issue by 404sand808s** [cymen/react-floating-label-input#12]
Hey, great little component here! Works very nicely. Wanted to know if there was a suggested way to style the component though, for instance I would like to control the color of the border as to change it if there is an error, etc.

**Comment by brandonFaf** [comment]
@404sand808s I created a PR #17 to make this easier. You can check it out and just pull it down locally if you need it before it gets merged in.

**Comment by 404sand808s** [comment]
Thank you very much!

**Comment by cymen** [comment]
4.2.0 is now published with the `className` PR merged.
