### ISSUE TITLE
how to do validation ?

### ISSUE THREAD

**Issue by almog-kiki** [cymen/react-floating-label-input#18]
how can I set the input is required and also check digits( e.g email. phone number) and limits characters?

**Comment by cymen** [comment]
So the props you pass in should end up on the `input` so you can add a `required` prop and it should make it's way through to the `input `tag. For the check, with the just merged `className` ability, you can do that yourself as you wish. If you think of a good way to do this, I would certainly be open to PRs but it should be solvable above this component.

**Comment by cymen** [comment]
4.2.0 is now published with the `className` PR merged.
