### ISSUE TITLE
article tag

### ISSUE THREAD

**Issue by obb12** [cymen/react-floating-label-input#20]
<article class="sc-bdVaJa UoSJW"><div class="sc-bwzfXH jXgUcd"><label for="example-3" class="sc-htpNat ilmQEB">Email</label><input id="example-3" name="email" class="sc-bxivhb bCmlkr"></div></article>
can you have something else so its valid html?

**Comment by obb12** [comment]
#21 proposed fix

**Comment by cymen** [comment]
Can you explain what problem it is you're trying to fix? Thanks!

**Comment by obb12** [comment]
Article tag has to have a h1 or something to be valid

**Comment by cymen** [comment]
Ah! I don't know why I used `article` -- I think I was still getting started with `styled-components`. I've merged your fix and pushed out 4.2.1. Thank you!
