### ISSUE TITLE
Textarea floating

### ISSUE THREAD

**Issue by obb12** [cymen/react-floating-label-input#22]
can there be a prop whether or not the input is a textarea?

**Comment by cymen** [comment]
You can try this by doing `npm run storybook` and then edit `src/main.js` to have `styled.textarea` instead of `styled.input` and I see there are some alignment issues with the prompt. It certainly is possible but it looks like it requires some work to do.

**Comment by cymen** [comment]
I forgot to say, I would find it useful to have support for textarea too.

**Comment by obb12** [comment]
https://codepen.io/netgloo/pen/JXreqJ i found this approach

**Comment by obb12** [comment]
#23

**Comment by cymen** [comment]
I'm thinking this over. The problem I have is just having a blank spot without any hint (besides the label) that it is a spot you can type is potentially confusing. I played with the codepen and have this:

https://codepen.io/cymen/pen/YzzwxKX

An example of textarea is at the bottom of the materio.io demo here:

https://material-components.github.io/material-components-web-catalog/#/component/text-field

So I'm thinking about that -- I do want to do this in a way that has good user experience.

**Comment by obb12** [comment]
Should it be a separate component?

**Comment by cymen** [comment]
I was debating same thing -- let's make it separate. I forked this component into:

https://github.com/cymen/react-floating-label-textarea

And I pulled your commit into that. I'll make my changes from the codepen and let's see if we're both happy with that and then go forward with that?

**Comment by cymen** [comment]
I tweaked it some more but it's not working quite right on the storybook. So needs more work. But let's work on it over there. I've got to step away for a while but will take another look later.

**Comment by obb12** [comment]
Is it because of the storybooks height and width?

**Comment by obb12** [comment]
is it available on yarn or npm?

**Comment by cymen** [comment]
I'm going to close this out now that https://github.com/cymen/react-floating-label-textarea is published to npm.
