### ISSUE TITLE
extend lib to select too

### ISSUE THREAD

**Issue by eladonline** [cymen/react-floating-label-input#3]
hey friend ty for this library it helped a lot 
I also needed the same thing for select, so I cloned your lib and modified it 
i would love to send you the code so others can use it too

**Comment by cymen** [comment]
Hi @eladonline it would be interesting to extend it to select. I've love to see what you have! Sorry for the slow response (I need to adjust my email filters -- I missed some messages from this repo).

**Comment by cymen** [comment]
Closing but PRs more than welcomed.
