### ISSUE TITLE
Password input is not working.

### ISSUE THREAD

**Issue by heybriancheung** [cymen/react-floating-label-input#6]
`<FloatingLabelInput type="password" onChange={(e) => this.setInput(e)} id="password" label="Password" />`
This does not make the input box a password input box.

**Comment by cymen** [comment]
`type` prop was not supported until just now with version 4.0.8 (added on this PR from @volaka 8de2723651579f344798fd071afcc2c42b511b9f). Please upgrade and it should work now!

**Comment by cymen** [comment]
(I think `type` was accidentally broken by an earlier change)

**Comment by cymen** [comment]
Please reopen if still an issue.

**Comment by heybriancheung** [comment]
Yes, work now. What's a coincidence that we are working on the same features a few minutes apart.

**Comment by cymen** [comment]
Oh, you actually reminded me to go get that PR in :).
