### ISSUE TITLE
When there is autofill, labels don't float

### ISSUE THREAD

**Issue by volaka** [cymen/react-floating-label-input#7]
If browser autofills the field, labels don't float.

How do we fix this, do you have any idea? If you need any help, I would be glad to help you.

<img width="644" alt="screen shot 2019-02-24 at 21 12 51" src="https://user-images.githubusercontent.com/13176256/53303230-0fdf4700-3879-11e9-895a-155412d6f29c.png">

**Comment by cymen** [comment]
I looked into this briefly and it looks like a potentially difficult problem to solve well:

https://stackoverflow.com/questions/11708092/detecting-browser-autofill

PRs are welcomed. I probably won't get to this soon. There are some good ideas in the above thread though and possibly the first step would be to have this component have an optional prop to be active so one could try these ideas outside of the component and then later try to add it as a feature? Just one thought I had. Or can solve it well for the browsers you care about and it can be an iterative thing to get as much supported as possible (doesn't have to be all at once).

**Comment by volaka** [comment]
@cymen Thanks for the answer. I will have a look to it when I get some time. Not an urgent problem but will be nice to fix.

**Comment by oaguilar5** [comment]
@cymen hi there, sorry if this is not part of this issue/thread or if there is an obvious solution I'm missing but this issue also occurs when passing a state object to the value prop. For example, the value references a state object 'this.state.myValue" like so:

`value={this.state.myValue}`

when 'myValue' changes through a state re-rendering, the input reflects the new value, but does not 'float' the label, similar to @volaka screenshot above. 

Is this the same issue or is there a way to trigger the re-render of the component?

**Comment by volaka** [comment]
@oaguilar5 sorry but I haven't used this repo for over a year. I can look at it but I have a tight schedule until end of the month. In this time, if you have a solution, we can look into it.

**Comment by cymen** [comment]
@oaguilar5 I merged #33 which may resolve the issue you were having. I believe it will? I'm going to close this out but if you find it does not, please reopen. Thank you.
