### ISSUE TITLE
when value set cannot change/delete/add characters 

### ISSUE THREAD

**Issue by almog-kiki** [cymen/react-floating-label-input#8]
when I set some value in the input with the "value" attribute I cannot change the value anymore.

**Comment by cymen** [comment]
You might want to use `defaultValue` if it's the initial value of the input. Does that solve your problem? Just asking before looking further in case that is what you're wanting.

**Comment by almog-kiki** [comment]
the onChange attribute was not clear. but finally, I succeed to do that. 
there is an option to limit input characters?

**Comment by cymen** [comment]
I'm glad you got it working. There is not an option to limit input characters. But you could implement that now if you're using `value` and `onChange`.
